/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./layouts/BaseLayout.vue')['default']
    BlankLayout: typeof import('./layouts/BlankLayout.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    InspBg: typeof import('./components/Inspira/InspParticlesBg.vue')['default']
    InspiraLiquidBg: typeof import('./components/Inspira/InspLiquidBg.vue')['default']
    InspLiquidBg: typeof import('./components/Inspira/InspLiquidBg.vue')['default']
    InspParticlesBg: typeof import('./components/Inspira/InspParticlesBg.vue')['default']
    InspPatternBg: typeof import('./components/Inspira/InspPatternBg.vue')['default']
    LayoutActions: typeof import('./layouts/_views/LayoutActions.vue')['default']
    LayoutMenu: typeof import('./layouts/_views/LayoutMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    VAsidePage: typeof import('./pages/_views/VAsidePage.vue')['default']
    VCard: typeof import('./pages/_views/VCard.vue')['default']
    VDictTag: typeof import('./pages/_views/VDictTag.vue')['default']
    VHomeBg: typeof import('./pages/_views/VHomeBg.vue')['default']
    VPage: typeof import('./pages/_views/VPage.vue')['default']
    VTabPage: typeof import('./pages/_views/VTabPage.vue')['default']
    ZeActions: typeof import('./components/ZeActions.vue')['default']
    ZeForm: typeof import('./components/ZeForm.vue')['default']
    ZeFormItem: typeof import('./components/ZeFormItem.vue')['default']
    ZeInput: typeof import('./components/ZeInput.vue')['default']
    ZeModal: typeof import('./components/ZeModal.vue')['default']
    ZePagination: typeof import('./components/ZePagination.vue')['default']
    ZeTable: typeof import('./components/ZeTable.vue')['default']
    ZeTableColumn: typeof import('./components/ZeTableColumn.vue')['default']
  }
}
